version: '1.0.{build}'

image: Visual Studio 2017
before_build:
  - nuget restore ./KenticoOnboardingApplication/KenticoOnboardingApplication.sln
  
build_script:
 - choco install "msbuild-sonarqube-runner" -y
 - MSBuild.SonarQube.Runner.exe begin /k:"VeronikaLou_kentico-onboarding-cs" /d:sonar.organization="veronikalou-github" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=2fd14fc4b9444b37f59642dbf29762879b753ff2"
 - msbuild "./KenticoOnboardingApplication/KenticoOnboardingApplication.sln"
 - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=2fd14fc4b9444b37f59642dbf29762879b753ff2"
  
test:
 assemblies:
   except:
    - ./KenticoOnboardingApplication/test/KenticoOnboardingApplication.Api.Tests/bin/Debug/KenticoOnboardingApplication.Tests.Base.dll
    - ./KenticoOnboardingApplication/test/KenticoOnboardingApplication.Services.Tests/bin/Debug/KenticoOnboardingApplication.Tests.Base.dll
    - ./KenticoOnboardingApplication/test/KenticoOnboardingApplication.Tests.Base/bin/Debug/KenticoOnboardingApplication.Tests.Base.dll